a = open("C:\\Users\\srika\\Desktop\\ACs.txt", "r")
print(a.read())
a.close()
f = open("C:\\Users\\srika\\Desktop\\Sri.txt", "w+")
f.write("Hi all, I'm M.Srikanth Reddy")
f.write(" Welcome to my page")
f.seek(0)
print(f.read())
f.close()
g = open("C:\\Users\\srika\\Desktop\\Sri.txt", "a+")#for appending data(eradicates the loss of previous data)
g.write("Hi all of You")
g.close()